COMPILE_OPTION= -Wall -Werror -g 
stack:
	g++ main.cc $(COMPILE_OPTION) -o stack.out 

conversion:
	g++ conversion.cc $(COMPILE_OPTION) -o conversion.out

check_bracket:
	g++ check_bracket.cc $(COMPILE_OPTION) -o check_bracket.out

line_edit:
	g++ line_edit.cc $(COMPILE_OPTION) -o line_edit.out

clean:
	rm *.out
